### ISSUE TITLE
Images will load when loop volume is checked

### ISSUE THREAD

**Issue by Arkirion** [CreativeMD/LittleFrames#76] opened 2024-03-15 20:45 UTC
As the title say, if you have "loop volume" checked, it will re-render image all the time, and its an issue because if you have several images ( lets say 20 ) it will consume 100% CPU

Work around is not put loop volume when you set an image, but anyways im doing the report because the bug still there.

![image](https://github.com/CreativeMD/LittleFrames/assets/67301108/3bd4dfa7-4c6c-4eee-9bc3-2383b69a723c)

![image](https://github.com/CreativeMD/LittleFrames/assets/67301108/22965fb9-e0d2-4f9d-8018-3d8de1ef6d23)

**Comment by SrRapero720** [comment] 2024-04-22 04:44
"loop" is the option, not "loop volume"
and CPU usage has nothing to do with picture rendering because pictures are already processed

**Comment by Arkirion** [comment] 2024-04-23 06:27
> "loop" is the option, not "loop volume" and CPU usage has nothing to do with picture rendering because pictures are already processed

Well, I dont know why is re-fetching the image but thats the bug and aparently re-fetch the image and load it again is consuming CPU usage enough to freeze my computer ( remember I have approximaly 20 images ) 

I just uncheck loop on images and that behavior stopped, have you tried to reproduce it? you might be the image blinks.

**Comment by CreativeMD** [comment] 2024-04-23 12:55
Cannot reproduce this issue. The image does not blink and my CPU usage does not go up. What version of minecraft/littleframes and watermedia are you using?

**Comment by SrRapero720** [comment] 2024-05-23 14:53
This was _partially addressed by watermedia_
For some reason imgur decide was a good idea redirect entirely to the main page direct image urls, failing to load and fallback to VLC just to render a picture. Not sure if the CPU usage was related (VLC doesn't consume too much hardware just to render a simple pic) but the watermedia fix should use the proper java decoder instead of fallback to VLC.

**Comment by SrRapero720** [comment] 2024-05-23 14:54
Again, doesn't solve the fact VLC is using too much CPU

**Closed as completed** 2024-05-25 09:22 UTC
