### ISSUE TITLE
Removing everything in the URL bar while a Youtube video is playing crashes the client for everyone who is near the frame.

### ISSUE THREAD

**Issue by MattyWalker1** [CreativeMD/LittleFrames#16] opened 2021-06-20 13:56 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.15_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 6/20/21 3:54 PM
Description: Rendering Block Entity

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@107a9490 rejected from java.util.concurrent.ThreadPoolExecutor@7c9454a7[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 15]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Unknown Source)
	at uk.co.caprica.vlcj.support.eventmanager.TaskExecutor.submit(TaskExecutor.java:68)
	at uk.co.caprica.vlcj.player.base.MediaPlayer.submit(MediaPlayer.java:264)
	at team.creative.littleframes.client.display.FrameVideoDisplay.release(FrameVideoDisplay.java:165)
	at team.creative.littleframes.common.structure.LittleFrame.renderTick(LittleFrame.java:179)
	at com.creativemd.littletiles.client.render.world.TileEntityTilesRenderer.render(TileEntityTilesRenderer.java:55)
	at com.creativemd.littletiles.client.render.world.TileEntityTilesRenderer.func_192841_a(TileEntityTilesRenderer.java:15)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:156)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:131)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Unknown Source)
	at uk.co.caprica.vlcj.support.eventmanager.TaskExecutor.submit(TaskExecutor.java:68)
	at uk.co.caprica.vlcj.player.base.MediaPlayer.submit(MediaPlayer.java:264)
	at team.creative.littleframes.client.display.FrameVideoDisplay.release(FrameVideoDisplay.java:165)
	at team.creative.littleframes.common.structure.LittleFrame.renderTick(LittleFrame.java:179)
	at com.creativemd.littletiles.client.render.world.TileEntityTilesRenderer.render(TileEntityTilesRenderer.java:55)
	at com.creativemd.littletiles.client.render.world.TileEntityTilesRenderer.func_192841_a(TileEntityTilesRenderer.java:15)

-- Block Entity Details --
Details:
	Name: minecraft:littletilestileentitytickingrendered // com.creativemd.littletiles.common.tileentity.TileEntityLittleTilesTickingRendered
	Block type: ID #261 (tile.null // com.creativemd.littletiles.common.block.BlockTile // littletiles:blocklittletilestickingrendered)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-169,69,176), Chunk: (at 7,4,0 in -11,11; contains blocks -176,0,176 to -161,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #261 (tile.null // com.creativemd.littletiles.common.block.BlockTile // littletiles:blocklittletilestickingrendered)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:156)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:131)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MattyWalker'/651, l='MpServer', x=-167.00, y=69.00, z=177.45]]
	Chunk stats: MultiplayerChunkCache: 2209, 2209
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-164,64,184), Chunk: (at 12,4,8 in -11,11; contains blocks -176,0,176 to -161,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 592 game time, 592 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 63 total; [EntityCreeper['Creeper'/4137, l='MpServer', x=-217.50, y=18.00, z=252.50], EntityRabbit['Rabbit'/82, l='MpServer', x=-214.50, y=69.00, z=239.50], EntityRabbit['Rabbit'/83, l='MpServer', x=-215.50, y=68.00, z=240.50], EntityRabbit['Rabbit'/84, l='MpServer', x=-214.50, y=69.00, z=235.50], EntityRabbit['Rabbit'/85, l='MpServer', x=-203.50, y=70.00, z=233.50], EntityRabbit['Rabbit'/86, l='MpServer', x=-201.50, y=70.00, z=232.50], EntityEnderman['Enderman'/6240, l='MpServer', x=-90.50, y=27.00, z=115.50], EntityPig['Pig'/103, l='MpServer', x=-173.50, y=71.00, z=119.50], EntityPig['Pig'/104, l='MpServer', x=-175.50, y=72.00, z=119.50], EntityPig['Pig'/105, l='MpServer', x=-174.50, y=72.00, z=119.50], EntityPig['Pig'/106, l='MpServer', x=-175.50, y=72.00, z=119.50], EntityRabbit['Rabbit'/115, l='MpServer', x=-160.50, y=71.00, z=255.50], EntityRabbit['Rabbit'/116, l='MpServer', x=-159.50, y=71.00, z=253.50], EntityCow['Cow'/136, l='MpServer', x=-116.50, y=67.00, z=196.50], EntityCow['Cow'/137, l='MpServer', x=-115.43, y=67.00, z=185.80], EntityCow['Cow'/138, l='MpServer', x=-119.50, y=67.00, z=196.50], EntityCow['Cow'/139, l='MpServer', x=-119.50, y=67.00, z=197.50], EntityRabbit['Rabbit'/147, l='MpServer', x=-91.50, y=69.00, z=244.50], EntityRabbit['Rabbit'/148, l='MpServer', x=-94.50, y=68.00, z=245.50], EntityRabbit['Rabbit'/149, l='MpServer', x=-92.50, y=68.00, z=238.50], EntityRabbit['Rabbit'/150, l='MpServer', x=-92.50, y=68.00, z=240.50], EntityRabbit['Rabbit'/151, l='MpServer', x=-92.50, y=68.00, z=242.50], EntityCreeper['Creeper'/6310, l='MpServer', x=-216.50, y=27.00, z=236.50], EntityCreeper['Creeper'/6311, l='MpServer', x=-215.50, y=27.00, z=236.50], EntityZombie['Zombie'/6411, l='MpServer', x=-197.50, y=57.00, z=213.50], EntityZombie['Zombie'/6412, l='MpServer', x=-200.50, y=57.00, z=214.50], EntityZombie['Zombie'/6430, l='MpServer', x=-228.50, y=13.00, z=109.50], EntityZombie['Zombie'/6431, l='MpServer', x=-229.50, y=13.00, z=109.50], EntityItem['item.item.seeds'/4555, l='MpServer', x=-217.77, y=65.00, z=173.11], EntityCreeper['Creeper'/6631, l='MpServer', x=-236.50, y=11.00, z=193.50], EntityCreeper['Creeper'/6632, l='MpServer', x=-237.50, y=11.00, z=194.50], EntityCreeper['Creeper'/6633, l='MpServer', x=-235.50, y=11.00, z=192.50], EntityBat['Bat'/6768, l='MpServer', x=-227.52, y=46.15, z=208.97], EntityBat['Bat'/6770, l='MpServer', x=-214.47, y=50.03, z=214.53], EntityBat['Bat'/4777, l='MpServer', x=-245.36, y=55.76, z=122.25], EntityItem['item.item.seeds'/6926, l='MpServer', x=-228.64, y=70.00, z=209.72], EntityItem['item.tile.doublePlant.sunflower'/6928, l='MpServer', x=-227.46, y=70.00, z=209.92], EntityItem['item.tile.doublePlant.sunflower'/6929, l='MpServer', x=-227.90, y=70.00, z=211.33], EntityZombie['Zombie'/5182, l='MpServer', x=-239.50, y=25.00, z=142.50], EntityZombie['Zombie'/5183, l='MpServer', x=-241.50, y=25.00, z=142.50], EntityPlayerSP['MattyWalker'/651, l='MpServer', x=-167.00, y=69.00, z=177.45], EntityBat['Bat'/3351, l='MpServer', x=-225.25, y=22.40, z=120.36], EntityBat['Bat'/3352, l='MpServer', x=-230.06, y=20.68, z=110.59], EntityBat['Bat'/3354, l='MpServer', x=-226.34, y=19.75, z=117.05], EntitySkeleton['Skeleton'/5449, l='MpServer', x=-216.50, y=26.00, z=241.50], EntityBat['Bat'/3595, l='MpServer', x=-114.94, y=51.00, z=128.42], EntitySkeleton['Skeleton'/3685, l='MpServer', x=-111.50, y=49.00, z=124.50], EntitySkeleton['Skeleton'/3686, l='MpServer', x=-110.50, y=49.00, z=125.50], EntityZombie['Zombie'/3687, l='MpServer', x=-107.50, y=49.00, z=124.50], EntitySkeleton['Skeleton'/5757, l='MpServer', x=-238.24, y=18.00, z=137.45], EntityZombieVillager['Zombie Villager'/3721, l='MpServer', x=-229.50, y=13.00, z=115.50], EntitySpider['Spider'/5790, l='MpServer', x=-242.50, y=18.00, z=139.50], EntitySkeleton['Skeleton'/5792, l='MpServer', x=-243.50, y=19.00, z=145.23], EntitySkeleton['Skeleton'/5797, l='MpServer', x=-233.50, y=20.00, z=108.50], EntitySkeleton['Skeleton'/5798, l='MpServer', x=-227.71, y=20.00, z=104.54], EntitySkeleton['Skeleton'/5799, l='MpServer', x=-230.50, y=20.00, z=104.29], EntitySkeleton['Skeleton'/5800, l='MpServer', x=-230.50, y=20.00, z=110.50], EntityCreeper['Creeper'/5853, l='MpServer', x=-224.83, y=21.00, z=106.52], EntitySkeleton['Skeleton'/3841, l='MpServer', x=-115.50, y=51.00, z=131.50], EntitySkeleton['Skeleton'/3842, l='MpServer', x=-114.50, y=51.00, z=129.50], EntitySkeleton['Skeleton'/3843, l='MpServer', x=-115.50, y=51.00, z=129.50], EntitySkeleton['Skeleton'/3844, l='MpServer', x=-119.50, y=51.00, z=131.50], EntityBat['Bat'/5933, l='MpServer', x=-219.06, y=42.15, z=236.04]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9987872736 bytes (9525 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 5 total; -Xms10240m -Xmx10240m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                  | Signature                                |
	|:------ |:----------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2855-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2855 | forge-1.12.2-14.23.5.2855-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                           | None                                     |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                           | None                                     |
	| LCHIJA | creativecore      | 1.10.0       | CreativeCore_v1.10.61_mc1.12.2.jar      | None                                     |
	| LCHIJA | littleframes      | 1.0.0        | LittleFrames_v1.0.8_mc1.12.2.jar        | None                                     |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles_v1.5.15_mc1.12.2.jar        | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.15_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.77' Renderer: 'NVIDIA GeForce RTX 2060/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.77, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: NewTextures
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

**Comment by CreativeMD** [comment] 2021-06-20 20:16
Duplicate of https://github.com/CreativeMD/LittleFrames/issues/6 Unfortunately there is nothing I can do to fix it.

**Closed by CreativeMD** 2021-06-20 20:16 UTC
