### ISSUE TITLE
Frequent crashing when reloading chunks

### ISSUE THREAD

**Issue by DannyParker0001** [CreativeMD/LittleFrames#20] opened 2021-09-04 09:56 UTC
It used to not be so bad, but the game is consistently crashing now with an error that happens a fair bit
```java
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:123]: JNA: Callback uk.co.caprica.vlcj.support.eventmanager.NativeEventManager$EventCallback@46effbd1 threw the following exception:
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@5648c2c6 rejected from java.util.concurrent.ThreadPoolExecutor@588f367f[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 14]
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at uk.co.caprica.vlcj.support.eventmanager.TaskExecutor.submit(TaskExecutor.java:68)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at uk.co.caprica.vlcj.player.base.MediaPlayer.submit(MediaPlayer.java:264)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at uk.co.caprica.vlcj.player.base.ResetMediaEventHandler.finished(ResetMediaEventHandler.java:36)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at uk.co.caprica.vlcj.player.base.events.MediaPlayerEndReachedEvent.notify(MediaPlayerEndReachedEvent.java:36)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at uk.co.caprica.vlcj.player.base.events.MediaPlayerEndReachedEvent.notify(MediaPlayerEndReachedEvent.java:28)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at uk.co.caprica.vlcj.support.eventmanager.NativeEventManager.raiseEvent(NativeEventManager.java:179)
[18:53:34] [media-events/INFO] [STDERR]: [com.sun.jna.Native$1:uncaughtException:124]: 	at uk.co.caprica.vlcj.support.eventmanager.NativeEventManager$EventCallback.callback(NativeEventManager.java:206)
[19:04:57] [Client thread/INFO] [mcjtylib_ng]: createInventoryReadyPacket: TileEntity is not a ClientCommandHandler!
[19:05:32] [Client thread/WARN] [minecraft/NetHandlerPlayClient]: Received passengers for unknown entity
[19:05:32] [Client thread/WARN] [minecraft/NetHandlerPlayClient]: Received passengers for unknown entity
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3df41849d3, pid=78132, tid=0x00007f3f9e1e0640
#
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libvlccore.so.9+0xb19d3]  vlc_object_hold+0x3
#
# Core dump written. Default location: /store/.local/share/multimc/instances/ATM_SSUSSY_BACCA/minecraft/core or core.78132
#
# An error report file with more information is saved as:
# /store/.local/share/multimc/instances/ATM_SSUSSY_BACCA/minecraft/hs_err_pid78132.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Process crashed with exitcode 6.
```
I'm assuming VLC is crashing, then ig the only thing you can do is push the bug upstream.

**Comment by CreativeMD** [comment] 2021-09-07 21:07
Duplicate of https://github.com/CreativeMD/LittleFrames/issues/6 sorry but this won't be fixed in 1.12.

**Closed by CreativeMD** 2021-09-07 21:07 UTC
